spring:
  application:
    name: usuarios_servicio
  datasource:
    url: jdbc:mysql://localhost:3306/viajes
    username: root
    password: Andrewseigokan9*
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8003